import { createPortal } from 'react-dom'

const SECTIONS = [
  {
    title: 'What Kairo does',
    body: 'Type any US ticker (or ETF) and Kairo pulls live quote data, candles, fundamentals, and news, then runs a model over the price action + technicals to produce a verdict, confidence score, entry, and stop loss — plus a follow-up chat for "why?" questions.',
  },
  {
    title: 'AI methodology',
    body: 'Recommendations are generated by Groq llama-3.3-70b-versatile. The model receives the latest 10 daily candles, RSI (14), MACD (12/26/9), Bollinger Bands (20, 2σ), 52-week range, market cap, P/E, EPS growth, and a 5-day price change — then is asked to weight by indicator confluence. The system prompt tells it to never default to HOLD unless conflicted, and never return exactly 60 confidence.',
  },
  {
    title: 'Data sources',
    body: 'Quotes, profile, metrics, news — Finnhub. Daily candles — Alpha Vantage (with Yahoo Finance fallback for symbols Finnhub doesn’t recognize). Options data — Polygon.io. Indicators (RSI, MACD, Bollinger, VWAP, SR) — computed client-side from the candle series. Account + watchlist + portfolio storage — Supabase.',
  },
  {
    title: 'Limitations & disclaimer',
    body: 'Kairo is for educational and informational purposes only. Nothing here is investment advice. Free-tier API caps and Groq throughput can cause delays. Quotes may be 15-min delayed depending on the exchange. The AI is good at structured analysis but can be confidently wrong — always cross-check before acting.',
  },
  {
    title: 'Privacy',
    body: 'Preferences, watchlist alerts, recent tickers, and chat history are saved to localStorage on this device. With an account, watchlist + portfolio + signal-change emails are stored in Supabase. No analytics beyond Vercel’s default Web Vitals.',
  },
]

export default function AboutModal({ open, onClose }) {
  if (!open) return null
  return createPortal(
    <div
      className="fixed inset-0 z-[110] flex items-center justify-center p-4 animate-fade"
      style={{ background: 'var(--c-overlay)' }}
      onMouseDown={onClose}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label="About Kairo"
        className="glass-strong relative w-full max-w-[560px] rounded-2xl overflow-hidden animate-enter flex flex-col"
        style={{ maxHeight: '85vh' }}
        onMouseDown={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-[var(--c-glass-border)]">
          <span className="text-[11px] font-semibold text-[var(--c-text-faint)] uppercase tracking-[0.14em]">
            About Kairo
          </span>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="text-[var(--c-text-faint)] hover:text-[var(--c-text)] transition-colors p-1 cursor-pointer"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M12 4L4 12M4 4l8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-5 flex flex-col gap-5">
          {SECTIONS.map(({ title, body }) => (
            <section key={title} className="flex flex-col gap-1.5">
              <h3 className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-[#22B585]">{title}</h3>
              <p className="text-[13px] leading-relaxed text-[var(--c-text)]/85">{body}</p>
            </section>
          ))}
          <p className="text-[11px] text-[var(--c-text-fainter)] pt-2 border-t border-[var(--c-glass-border)]">
            Press <kbd className="font-mono text-[10px] font-bold border border-[var(--c-border-strong)] rounded px-1.5 py-0.5 leading-none">⌘K</kbd> anywhere to open the command palette.
          </p>
        </div>
      </div>
    </div>,
    document.body,
  )
}
