import DataTimestamp from './DataTimestamp'
import InfoTooltip from './InfoTooltip'

function ConfidenceRing({ confidence }) {
  const s     = typeof confidence === 'number' && !isNaN(confidence) ? Math.min(100, Math.max(0, confidence)) : 0
  const color = s >= 65 ? '#1D9E75' : s >= 45 ? '#d4922a' : '#e24b4a'
  const circ  = 2 * Math.PI * 22
  return (
    <div className="flex items-center gap-4 shrink-0">
      <div className="relative w-14 h-14">
        <svg className="w-14 h-14 -rotate-90" viewBox="0 0 56 56">
          <circle cx="28" cy="28" r="22" fill="none" stroke="#1a2e1f" strokeWidth="4.5" />
          <circle
            cx="28" cy="28" r="22" fill="none"
            stroke={color} strokeWidth="4.5"
            strokeLinecap="round"
            strokeDasharray={circ}
            strokeDashoffset={circ * (1 - s / 100)}
            style={{ transition: 'stroke-dashoffset 1s cubic-bezier(0.16,1,0.3,1)' }}
          />
        </svg>
        <span className="absolute inset-0 flex items-center justify-center text-sm font-black tabular-nums" style={{ color }}>
          {s}
        </span>
      </div>
      <div className="flex flex-col gap-0.5">
        <span className="text-[11px] text-[var(--c-text-faint)] uppercase tracking-[0.12em] font-semibold">Confidence</span>
        <span className="text-xs text-[var(--c-text-faint)]">out of 100</span>
      </div>
    </div>
  )
}

function Skeleton() {
  return (
    <div className="w-full glass-card rounded-2xl p-6 flex flex-col gap-5">
      <div className="flex items-center gap-2">
        <div className="w-1.5 h-1.5 rounded-full bg-[#1D9E75] animate-pulse" />
        <div className="h-2.5 w-28 rounded-full shimmer" />
      </div>
      <div className="flex gap-4 items-center">
        <div className="w-14 h-14 rounded-full shimmer shrink-0" />
        <div className="flex-1 flex flex-col gap-2">
          <div className="h-3 rounded-full shimmer w-4/5" />
          <div className="h-3 rounded-full shimmer w-3/5" />
          <div className="h-3 rounded-full shimmer w-2/3" />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div className="h-16 rounded-xl shimmer" />
        <div className="h-16 rounded-xl shimmer" />
      </div>
    </div>
  )
}

export default function AIAnalysis({ data, loading, asOf }) {
  if (loading) return <Skeleton />
  if (!data) return (
    <div className="w-full glass-card rounded-2xl p-6 flex flex-col gap-3 animate-enter">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <span className="text-[11px] font-semibold text-[var(--c-text-faint)] uppercase tracking-[0.12em]">AI Analysis</span>
        <span className="text-[9px] font-bold tracking-widest uppercase text-[var(--c-text-faint)] border border-[var(--c-border)] rounded-full px-2 py-0.5">Unavailable</span>
      </div>
      <div className="flex items-start gap-3">
        <span className="shrink-0 w-9 h-9 rounded-full bg-[var(--c-input-bg)] border border-[var(--c-input-border)] text-[var(--c-text-fainter)] flex items-center justify-center text-base">i</span>
        <div className="flex flex-col gap-1">
          <p className="text-sm text-[var(--c-text)]/80">AI analysis isn&apos;t available for this ticker right now.</p>
          <p className="text-xs text-[var(--c-text-faint)] leading-relaxed">Penny stocks, ADRs, and instruments with insufficient candle history are skipped. Try a major ticker (e.g. AAPL, NVDA, TSLA).</p>
        </div>
      </div>
    </div>
  )

  const isBuy  = data.verdict === 'BUY'
  const isHold = data.verdict === 'HOLD'
  const verdictColor  = isBuy ? '#1D9E75' : isHold ? '#d4922a' : '#e24b4a'
  const verdictLabel  = isBuy ? '▲ BUY' : isHold ? '◆ HOLD' : '▼ SELL'
  const verdictBorder = isBuy  ? 'border-[#1D9E75]/25 text-[#1D9E75] bg-[#1D9E75]/10'
                      : isHold ? 'border-[#d4922a]/25 text-[#d4922a] bg-[#d4922a]/10'
                      : 'border-[#e24b4a]/25 text-[#e24b4a] bg-[#e24b4a]/10'

  return (
    <div className="w-full glass-card rounded-2xl p-6 flex flex-col gap-5 animate-enter">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <span className="text-[11px] font-semibold text-[var(--c-text-faint)] uppercase tracking-[0.12em] inline-flex items-center">
          AI Analysis
          <InfoTooltip>
            Generated by Groq LLaMA-3.3-70B over technical indicators (RSI, MACD, Bollinger bands), recent price action, and fundamentals. Educational only — not financial advice.
          </InfoTooltip>
        </span>
        <span className={`px-3 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-widest border ${verdictBorder}`}>
          {verdictLabel}
        </span>
      </div>

      {/* Confidence ring + summary */}
      <div className="flex items-start gap-4">
        <ConfidenceRing confidence={data.confidence} />
        <p className="text-sm text-[var(--c-text)]/80 leading-relaxed flex-1 pt-0.5">{data.summary}</p>
      </div>

      {/* Bull / Bear split */}
      {(data.bullCase || data.bearCase) && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {data.bullCase && (
            <div className="bg-[#1D9E75]/[0.05] border border-[#1D9E75]/15 rounded-xl p-3.5 transition-colors hover:border-[#1D9E75]/25 hover:bg-[#1D9E75]/[0.08]">
              <p className="text-[10px] text-[#1D9E75] font-bold uppercase tracking-widest mb-2">Bull Case</p>
              <p className="text-xs text-[var(--c-text)]/60 leading-relaxed">{data.bullCase}</p>
            </div>
          )}
          {data.bearCase && (
            <div className="bg-[#e24b4a]/[0.05] border border-[#e24b4a]/15 rounded-xl p-3.5 transition-colors hover:border-[#e24b4a]/25 hover:bg-[#e24b4a]/[0.08]">
              <p className="text-[10px] text-[#e24b4a] font-bold uppercase tracking-widest mb-2">Bear Case</p>
              <p className="text-xs text-[var(--c-text)]/60 leading-relaxed">{data.bearCase}</p>
            </div>
          )}
        </div>
      )}

      {/* Bollinger explanation */}
      {data.bollingerExplanation && (
        <div className="bg-[var(--c-input-bg)] border border-[var(--c-input-border)] rounded-xl p-3.5 transition-colors hover:border-[var(--c-border-strong)]">
          <p className="text-[10px] text-[var(--c-text-faint)] font-bold uppercase tracking-widest mb-1.5">Bollinger Bands</p>
          <p className="text-xs text-[var(--c-text)]/60 leading-relaxed">{data.bollingerExplanation}</p>
        </div>
      )}

      {/* Candle pattern */}
      {data.candlePatternMeaning && (
        <div className="bg-[var(--c-input-bg)] border border-[var(--c-input-border)] rounded-xl p-3.5 transition-colors hover:border-[var(--c-border-strong)]">
          <p className="text-[10px] text-[var(--c-text-faint)] font-bold uppercase tracking-widest mb-1.5">Candle Pattern</p>
          <p className="text-xs text-[var(--c-text)]/60 leading-relaxed">{data.candlePatternMeaning}</p>
        </div>
      )}

      {/* Trade idea */}
      {data.tradeIdea && (
        <div className="border-l-2 border-[#1D9E75]/40 pl-4 py-0.5">
          <p className="text-[10px] text-[#1D9E75] font-bold uppercase tracking-widest mb-1.5">Trade Idea</p>
          <p className="text-sm text-[var(--c-text)]/80 leading-relaxed">{data.tradeIdea}</p>
        </div>
      )}

      {/* Footer — data freshness */}
      {asOf && (
        <div className="flex items-center justify-end pt-3 -mb-1 border-t border-[var(--c-border)]/60">
          <DataTimestamp asOf={asOf} source="Groq" />
        </div>
      )}
    </div>
  )
}
