import { useEffect, useState } from 'react'
import DataTimestamp from './DataTimestamp'
import InfoTooltip from './InfoTooltip'

const ERROR_REVEAL_DELAY_MS = 4000

// The panel's job is to interpret each indicator IN ISOLATION and then
// name the confluence. This is deliberately a different mental model than
// the Recommendation panel's punchy verdict — one is a diagnosis, this
// one is the specialist's full workup.

// Verdict pill in the header — the verdict itself comes from the sibling
// verdict call so the two panels stay in sync on the call, even though
// their prose is generated by different prompts.
function VerdictPill({ verdict }) {
  if (!verdict) return null
  const cfg = verdict === 'BUY'
    ? { label: '▲ BUY',  className: 'border-[#22B585]/25 text-[#22B585] bg-[#22B585]/10' }
    : verdict === 'HOLD'
    ? { label: '◆ HOLD', className: 'border-[#e3a234]/25 text-[#e3a234] bg-[#e3a234]/10' }
    : { label: '▼ SELL', className: 'border-[#ef5454]/25 text-[#ef5454] bg-[#ef5454]/10' }
  return (
    <span className={`px-3 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-widest border ${cfg.className}`}>
      {cfg.label}
    </span>
  )
}

function Skeleton({ showSlowMessage }) {
  return (
    <div className="w-full glass-card rounded-xl p-4 sm:p-5 flex flex-col gap-4 animate-fade">
      <div className="flex items-center gap-2">
        <div className="w-1.5 h-1.5 rounded-full bg-[#22B585] animate-pulse" />
        <div className="h-2.5 w-32 rounded-full shimmer" />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {[1, 2, 3, 4].map(i => (
          <div key={i} className="flex flex-col gap-1.5 p-3 rounded-xl border border-[var(--c-input-border)] bg-[var(--c-input-bg)]">
            <div className="h-2 w-16 rounded-full shimmer" />
            <div className="h-3 w-4/5 rounded-full shimmer" />
            <div className="h-3 w-3/5 rounded-full shimmer" />
          </div>
        ))}
      </div>
      {showSlowMessage && (
        <p className="text-[12px] text-[var(--c-text-faint)] italic mt-1 animate-fade">
          Detailed technical analysis loading — the specialist's write-up takes a beat.
        </p>
      )}
    </div>
  )
}

function Unavailable({ error }) {
  const msg =
    error && /timeout|timed out|504|gateway/i.test(error)
      ? 'Detailed analysis timed out. Try refreshing — Groq can lag on cold starts.'
      : error && /candle|simulated|insufficient.*history/i.test(error)
      ? 'Real candle data is unavailable, so the specialist has nothing to read. Analysis will resume once live OHLC returns.'
      : 'Detailed analysis temporarily unavailable. Try refreshing in a moment.'
  return (
    <div className="w-full glass-card rounded-xl p-4 sm:p-5 flex flex-col gap-3 animate-fade">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <span className="text-[11px] font-semibold text-[var(--c-text-faint)] uppercase tracking-[0.12em]">AI Analysis</span>
        <span className="text-[9px] font-bold tracking-widest uppercase text-[var(--c-text-faint)] border border-[var(--c-border)] rounded-full px-2 py-0.5">Unavailable</span>
      </div>
      <div className="flex items-start gap-3">
        <span className="shrink-0 w-9 h-9 rounded-full bg-[var(--c-input-bg)] border border-[var(--c-input-border)] text-[var(--c-text-fainter)] flex items-center justify-center text-base">i</span>
        <p className="text-sm text-[var(--c-text)]/85 leading-relaxed">{msg}</p>
      </div>
    </div>
  )
}

// One row per indicator. Label on the left, prose on the right. Consistent
// tile styling with the tiles used in IndicatorsGrid — same border, same
// hover, same padding — so the two panels feel like siblings.
function IndicatorRow({ label, text, accent }) {
  if (!text || (typeof text === 'string' && text.trim() === '')) return null
  return (
    <div className="flex flex-col gap-1.5 p-3 rounded-xl border border-[var(--c-input-border)] bg-[var(--c-input-bg)] transition-colors hover:border-[var(--c-border-strong)]">
      <p
        className="text-[10px] font-bold uppercase tracking-widest"
        style={{ color: accent ?? 'var(--c-text-faint)' }}
      >
        {label}
      </p>
      <p className="text-[12.5px] leading-relaxed text-[var(--c-text)]/85">{text}</p>
    </div>
  )
}

export default function AIAnalysis({ data, loading, error, asOf, verdict }) {
  const [revealError, setRevealError] = useState(false)
  useEffect(() => {
    if (data || loading) { setRevealError(false); return }
    const id = setTimeout(() => setRevealError(true), ERROR_REVEAL_DELAY_MS)
    return () => clearTimeout(id)
  }, [data, loading, error])

  const [slowLoad, setSlowLoad] = useState(false)
  useEffect(() => {
    if (!loading) { setSlowLoad(false); return }
    const id = setTimeout(() => setSlowLoad(true), 3000)
    return () => clearTimeout(id)
  }, [loading])

  if (!data) {
    if (loading || !revealError) return <Skeleton showSlowMessage={slowLoad} />
    return <Unavailable error={error} />
  }

  // Every field here comes from the DETAILED prompt — a different Groq
  // call than the one behind the Recommendation card. Numbers are the
  // same (fed from the same market context) but the interpretation is
  // per-indicator and independent, not verdict-driven.
  const {
    rsiAnalysis,
    macdAnalysis,
    bbAnalysis,
    vwapAnalysis,
    volumeAnalysis,
    indicatorConfluence,
    rangeContext,
    fundamentalContext,
  } = data

  return (
    <div className="w-full glass-card rounded-xl p-4 sm:p-5 flex flex-col gap-4 animate-enter">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-2">
        <span className="text-[11px] font-semibold text-[var(--c-text-faint)] uppercase tracking-[0.12em] inline-flex items-center">
          AI Analysis
          <InfoTooltip>
            Per-indicator breakdown from Groq LLaMA-3.3. This panel INTERPRETS each indicator in isolation — the verdict itself lives in the AI Recommendation panel above. Educational only.
          </InfoTooltip>
        </span>
        <VerdictPill verdict={verdict} />
      </div>

      {/* Per-indicator grid — each cell speaks about ONE indicator only. */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <IndicatorRow label="RSI (14)"           text={rsiAnalysis}    accent="#22B585" />
        <IndicatorRow label="MACD"               text={macdAnalysis}   accent="#22B585" />
        <IndicatorRow label="Bollinger Bands"    text={bbAnalysis}     accent="#22B585" />
        <IndicatorRow label="VWAP"               text={vwapAnalysis}   accent="#22B585" />
        <IndicatorRow label="Volume Trend"       text={volumeAnalysis} accent="#22B585" />
      </div>

      {/* Confluence — where the indicators agree vs contradict. Called
          out separately with an amber left rail because this is the
          panel's most valuable synthesis. */}
      {indicatorConfluence && indicatorConfluence.trim() && (
        <div className="border-l-2 border-[#e3a234]/60 pl-4 py-1">
          <p className="text-[10px] text-[#e3a234] font-bold uppercase tracking-widest mb-1.5">Indicator Confluence</p>
          <p className="text-[13px] text-[var(--c-text)]/85 leading-relaxed">{indicatorConfluence}</p>
        </div>
      )}

      {/* Range and fundamentals — situate the technical read in a wider frame. */}
      {(rangeContext || (fundamentalContext && fundamentalContext.trim())) && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {rangeContext && rangeContext.trim() && (
            <div className="flex flex-col gap-1.5 p-3 rounded-xl border border-[var(--c-input-border)] bg-[var(--c-input-bg)] transition-colors hover:border-[var(--c-border-strong)]">
              <p className="text-[10px] text-[var(--c-text-faint)] font-bold uppercase tracking-widest">52W Range Context</p>
              <p className="text-[12.5px] text-[var(--c-text)]/85 leading-relaxed">{rangeContext}</p>
            </div>
          )}
          {fundamentalContext && fundamentalContext.trim() && (
            <div className="flex flex-col gap-1.5 p-3 rounded-xl border border-[var(--c-input-border)] bg-[var(--c-input-bg)] transition-colors hover:border-[var(--c-border-strong)]">
              <p className="text-[10px] text-[var(--c-text-faint)] font-bold uppercase tracking-widest">Fundamentals</p>
              <p className="text-[12.5px] text-[var(--c-text)]/85 leading-relaxed">{fundamentalContext}</p>
            </div>
          )}
        </div>
      )}

      {/* Footer — data freshness */}
      {asOf && (
        <div className="flex items-center justify-end pt-3 -mb-1 border-t border-[var(--c-border)]/60">
          <DataTimestamp asOf={asOf} source="Groq" />
        </div>
      )}
    </div>
  )
}
